name: Deploy Weather API

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies & test
        run: |
          pip install -r backend/requirements.txt
          python -c "import flask, requests; print('✅ Flask & Requests OK')"

      - name: Build Docker image
        run: docker build -t weather-api ./backend

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          debug: true
          script: |
            cd /home/ubuntu/weather-api
            docker stop weather-api || true
            docker rm weather-api || true
            docker build -t weather-api ./backend
            docker run -d --name weather-api -p 5000:5000 -e OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }} weather-api